=== BlueDiamond/SOAPService/soap-service/src/main/resources/wsdl/User_Profile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://soai.com/types" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified" targetNamespace="http://soai.com/types">

    <xs:element name="UserProfileResponse">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="1">
                <xs:element name="User_Profile" type="User_Profile_Type"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="User_Profile_Type">
        <xs:all>
            <xs:element name="Profile_ID" type="xs:integer"/>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Email_ID" type="xs:string"/>
            <xs:element name="Sex" type="xs:string"/>
            <xs:element name="Relationship_Status" type="xs:string"/>
            <xs:element name="Languages" type="xs:string"/>
            <xs:element name="Lives_in" type="xs:string"/>
            <xs:element name="Created_TS" type="xs:dateTime"/>
        </xs:all>
    </xs:complexType>

</xs:schema>

=== BlueDiamond/SOAPService/soap-service/src/main/resources/wsdl/User_Profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<UserProfileResponse xmlns="http://soai.com/types" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://soai.com/types User_Profile.xsd">
    <User_Profile>
        <Profile_ID>101</Profile_ID>
        <Name>Palanisamy Ramamoorthy</Name>
        <Email_ID>rpalanisamy@yahoo.com</Email_ID>
        <Sex>male</Sex>
        <Relationship_Status>married</Relationship_Status>
        <Languages>English, Hindi, Tamil</Languages>
        <Lives_in>Malvern, PA</Lives_in>
        <Created_TS>2013-03-30T09:30:10.5</Created_TS>
    </User_Profile>
    
    <User_Profile>
        <Profile_ID>102</Profile_ID>
        <Name>Brian Charles</Name>
        <Email_ID>praharam@gmail.com</Email_ID>
        <Sex>male</Sex>
        <Relationship_Status>Single</Relationship_Status>
        <Languages>Spanish, English</Languages>
        <Lives_in>Orlando, FL</Lives_in>
        <Created_TS>2013-03-30T09:30:10.5</Created_TS>
    </User_Profile>
</UserProfileResponse>
